# Generated by Django 5.0.3 on 2024-03-30 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task4', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('nationality', models.CharField(max_length=100)),
                ('experience_years', models.PositiveIntegerField()),
                ('number_of_managed_clubs', models.PositiveIntegerField()),
                ('number_of_titles_won', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='away_team_attacks',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='away_team_clearances_completed',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='away_team_corner_kicks',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='away_team_dangerous_attacks',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='away_team_fouls',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='away_team_free_kicks',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='away_team_goalkeeper_saves',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='away_team_offsides',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='away_team_red_cards',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='away_team_tackles',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='away_team_throw_ins',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='away_team_total_passes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='away_team_yellow_cards',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='home_team_attacks',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='home_team_clearances_completed',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='home_team_corner_kicks',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='home_team_dangerous_attacks',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='home_team_fouls',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='home_team_free_kicks',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='home_team_goalkeeper_saves',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='home_team_offsides',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='home_team_red_cards',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='home_team_tackles',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='home_team_throw_ins',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='home_team_total_passes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='matchstatistic',
            name='home_team_yellow_cards',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=30)),
                ('player_age', models.PositiveIntegerField()),
                ('player_nationality', models.CharField(max_length=20)),
                ('player_position', models.CharField(max_length=15)),
                ('player_yellow_cards', models.PositiveIntegerField()),
                ('player_red_cards', models.PositiveIntegerField()),
                ('market_value', models.PositiveIntegerField()),
                ('contract_expires', models.DateField()),
                ('player_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_name', to='task4.team')),
            ],
        ),
    ]
