# Generated by Django 5.0.3 on 2024-03-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task4', '0002_coach_alter_matchstatistic_away_team_attacks_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
