# Generated by Django 5.0.3 on 2024-03-30 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task4', '0004_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_starts', models.DateTimeField()),
                ('points', models.PositiveIntegerField()),
                ('match_count', models.PositiveIntegerField()),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_standing_name', to='task4.player')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_standing_name', to='task4.team')),
            ],
        ),
    ]
