# Generated by Django 5.0.3 on 2024-03-30 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task4', '0005_standings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopScorers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.CharField(max_length=100)),
                ('goals', models.PositiveIntegerField()),
                ('assists', models.PositiveIntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_name', to='task4.team')),
            ],
        ),
        migrations.CreateModel(
            name='Transfermarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('from_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamname', to='task4.team')),
                ('market_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketvalue', to='task4.player')),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playername', to='task4.player')),
                ('to_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamtoname', to='task4.team')),
            ],
        ),
    ]
