# Generated by Django 5.0.3 on 2024-03-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task4', '0006_topscorers_transfermarket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topscorers',
            options={'verbose_name': 'Top Scorers', 'verbose_name_plural': 'Top Scorers'},
        ),
        migrations.AlterModelOptions(
            name='transfermarket',
            options={'verbose_name': 'Transfer Market', 'verbose_name_plural': 'Transfer Market'},
        ),
        migrations.RemoveField(
            model_name='player',
            name='market_value',
        ),
        migrations.AlterField(
            model_name='transfermarket',
            name='market_value',
            field=models.PositiveIntegerField(),
        ),
    ]
