# Generated by Django 5.0.3 on 2024-03-30 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task4', '0007_alter_topscorers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topscorers',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_topscorer', to='task4.player'),
        ),
        migrations.AlterField(
            model_name='topscorers',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_topscorer', to='task4.team'),
        ),
        migrations.AlterField(
            model_name='transfermarket',
            name='from_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_name', to='task4.team'),
        ),
        migrations.AlterField(
            model_name='transfermarket',
            name='player_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_transfermarket', to='task4.player'),
        ),
        migrations.AlterField(
            model_name='transfermarket',
            name='to_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_to_name', to='task4.team'),
        ),
    ]
