# Generated by Django 5.0.3 on 2024-03-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task4', '0008_alter_topscorers_player_alter_topscorers_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topscorers',
            name='team',
        ),
    ]
