# Generated by Django 5.0.3 on 2024-03-30 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task4', '0009_remove_topscorers_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='standings',
            options={'verbose_name': 'Standings', 'verbose_name_plural': 'Standings'},
        ),
        migrations.RemoveField(
            model_name='standings',
            name='match_count',
        ),
        migrations.RemoveField(
            model_name='standings',
            name='match_starts',
        ),
        migrations.RemoveField(
            model_name='standings',
            name='squad',
        ),
        migrations.AddField(
            model_name='standings',
            name='draws',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standings',
            name='goal_diff',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standings',
            name='lose',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standings',
            name='matches_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='standings',
            name='win',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='standings',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
