# Generated by Django 5.0.3 on 2024-03-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task4', '0010_alter_standings_options_remove_standings_match_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='coach',
            name='number_of_titles_won',
        ),
        migrations.AddField(
            model_name='coach',
            name='titles_won',
            field=models.ManyToManyField(related_name='title_coach', to='task4.title'),
        ),
    ]
