# Generated by Django 5.0.3 on 2024-03-31 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task4', '0012_alter_coach_options_alter_match_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfermarket',
            old_name='player_name',
            new_name='player',
        ),
    ]
