# Generated by Django 5.0.3 on 2024-03-31 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task4', '0014_rename_player_transfermarket_player_transfer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='player_name',
            new_name='name',
        ),
    ]
