# Generated by Django 5.0.3 on 2024-03-31 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task4', '0015_rename_player_name_player_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='player_name',
        ),
        migrations.RenameField(
            model_name='transfermarket',
            old_name='player_transfer_name',
            new_name='player_name',
        ),
    ]
