# Generated by Django 5.0.3 on 2024-03-31 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task4', '0016_rename_name_player_player_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfermarket',
            name='from_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='task4.team'),
        ),
        migrations.AlterField(
            model_name='transfermarket',
            name='to_club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='task4.team'),
        ),
    ]
