# Generated by Django 5.0.3 on 2024-03-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task4', '0017_alter_transfermarket_from_club_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_age',
        ),
        migrations.AddField(
            model_name='player',
            name='player_birthday',
            field=models.DateField(default='2000-01-01'),
            preserve_default=False,
        ),
    ]
